---
title: Laravel Spin Template with Queue and Reverb
authors:
  - Prabhjyot Singh (@ps-prabhjyotsingh)
description: The Laravel Spin template with queue and reverb pre-configured
repository: https://github.com/ps-prabhjyotsingh
issues: https://github.com/ps-prabhjyotsingh/spin-template-laravel-basic/issues
